### ISSUE TITLE
Can't build, missing file and manifest referencing mt6852 instead

### ISSUE THREAD

**Issue by kth5** [rohantaneja/proprietary_vendor_lenovo#2]
Seems I cannot follow the basic build instructions without first adjusting .repo/manifest.xml to use the mt6572 repositories. Then I run into the following issue during brunch:

> ~/android/system# brunch cm_mt6752-userdebug
> including vendor/cm/vendorsetup.sh
> build/core/product_config.mk:239: **\* _nic.PRODUCTS.[[device/lenovo/mt6752/cm.mk]]: "vendor/lenovo/mt6752/mt6752-blobs.mk" does not exist.  Stop.
> Device mt6752 not found. Attempting to retrieve device repository from CyanogenMod Github >(http://github.com/CyanogenMod).
> Repository for mt6752 not found in the CyanogenMod Github repository list. If this is in error, you >may need to manually add it to your local_manifests/roomservice.xml.
> build/core/product_config.mk:239: **\* _nic.PRODUCTS.[[device/lenovo/mt6752/cm.mk]]: >"vendor/lenovo/mt6752/mt6752-blobs.mk" does not exist.  Stop.
> 
> *\* Don't have a product spec for: 'cm_mt6752'
> *\* Do you have the right repo manifest?
> 
> No such item in brunch menu. Try 'breakfast'

I can comment the call to inherit mt6752-blobs.mk and get a bit further but will (obviously?) not get a working image.

Any help would be appreciated.

PS: I'm trying to produce a A7000 Plus build using this as a base.

**Comment by rohantaneja** [comment]
mt6752-blobs.mk -> mt6752-vendor.mk
